### ISSUE TITLE
Here i go again

### ISSUE THREAD

**Issue by dinism** [wjunkin/moodle-quiz_liveviewgrid#18] opened 2019-06-14 11:51 UTC
The text of the buton is hardcoded.
Sorry about this.
![imagem](https://user-images.githubusercontent.com/14828021/59507474-0bc84b00-8ea3-11e9-95cb-40a72fba1d31.png)

**And what about this phenomenon?**
![imagem](https://user-images.githubusercontent.com/14828021/59507729-d112e280-8ea3-11e9-897a-1f855d1d4485.png)

**Take a look here!**
![imagem](https://user-images.githubusercontent.com/14828021/59507997-68783580-8ea4-11e9-9795-77eb635938fd.png)

**Comment by wjunkin** [comment] 2019-06-14 13:15
Thanks for catching this. I have corrected the code (added in the needed language string). You will need to clear cache. I don't know how to align the text in a button with other text but I will work on this. You noted that the time in the program and the time in the computer were different. This may be caused by the time on the server being slightly different from the clock in the computer.

**Comment by dinism** [comment] 2019-06-15 11:18
In your recent added code (commit 315163d):
$string['newpage'] = "New page, static & printable";
**Should be(?)**
$string['newpage'] = 'New page, static & printable';

**Comment by dinism** [comment] 2019-06-15 11:54
When you are in a STATIC page and if you select other group you **GO BACK**. It opens the principal page in static page tab of the browser with goup you selected.
The same happens when you viewing a single question on a static page and you select other question.
If it's not possible change group or question i think it's better not show the option to change group or question. **It's only my opinion**.

**Comment by dinism** [comment] 2019-06-15 12:04
Take a look to messages in the images:
![imagem](https://user-images.githubusercontent.com/14828021/59551169-3bdc2080-8f6d-11e9-806e-3a94affa64ac.png)
![imagem](https://user-images.githubusercontent.com/14828021/59551171-45658880-8f6d-11e9-9523-b0d962ff82c9.png)
**Take a look to number 1,2 and 3. Why this happens?**
User1 name = "João" + surname = "Cabeça Branca" ► João Cabeça Branca. It adjust to column width.
User2 name = "Ruben" + surname = "Cerqueira" ► Ruben Cerqueira. It **DON'T** adjust to  column width
User3 name = "Rodrigo" + surname = "Morganheira" ► Rodrigo Morganheira. It **DON'T** adjust to  column width

**Comment by wjunkin** [comment] 2019-06-15 12:38
Thanks for your comments and suggestions. I am on vacation for a week and will see what I can do when I'm back home.

**Comment by wjunkin** [comment] 2019-06-16 02:10
Hi, 
I like your suggestion that I remove all links and options that allow teachers to go from a static page to any other page. I think navigation will be much cleaner and easier for teachers to understand if all navigation to a static page goes from the dynamic page. I am on vacation but will make this change in a week.

**Comment by wjunkin** [comment] 2019-06-21 18:27
Hi, Dinis,
I think that the new version has taken care of two of the issues that you mentioned. I think that the timing issue (if I understand your comment correctly) is just caused by a difference in the time on the server vs the time on your computer. Also, I think the current version has used your suggestion about making the navigation much clearer and cleaner (thank you very much). Based on this I am closing this issue but please feel free to let me know if this or anything else should be changed and thanks for your help.

**Closed as completed by wjunkin** 2019-06-21 18:27 UTC

**Comment by dinism** [comment] 2019-06-21 21:24
Hi
But where is the new version? Last commit 7 days ago.
![image](https://user-images.githubusercontent.com/14828021/59952219-4e75be80-9473-11e9-8ba6-37547ee8dc75.png)

**Comment by wjunkin** [comment] 2019-06-22 00:15
My fault, Dinis,
I wrote my email to you before I finished the commit to this site and then I stopped to watch the Women's World Cup Soccer. The new version has been posted here now.
