### ISSUE TITLE
UTF-8?

### ISSUE THREAD

**Issue by dinism** [wjunkin/moodle-quiz_liveviewgrid#12] opened 2019-05-02 23:15 UTC
In normal view of the table, the response is:
fenótipo, genótipo, gene.
In compact view it shows:
fen�
In portuguese we have accented words. Is this a "my error"?
Thanks for the plugin

**Comment by wjunkin** [comment] 2019-05-03 02:47
Hi, Dinis,
Thanks for your interest in LIve Report and for your kind words. 
I plan to take care of this problem very promptly. However, I would like to be able to test out any changes that I make to verify that the problem has been solved. My suggestion is that I set you up as a student in a test course where I can study things very carefully. You can then enter the answer to a quiz with the Portuguese words and I can see how they are not displayed correctly in Live Report and then make the changes to correct this problem. Does this sound like a good plan? 
If you want to communicage directly with me, my email address is junkinwf@eckerd.edu. However, we can also communicate via this github site if you prefer.
Again thanks.
Bill Junkin

**Comment by dinism** [comment] 2019-05-03 08:08
Once again THANKS a lot.
As i said before i USE your plugin and i'm PT-PT translator.
I'm testing version 1.2.5 of plugin in Moodle 3.6.3.
In plugins directory of Moodle the last version is Release v1.1.4 (2019030500) for Moodle 3.2+
About your plan, of course i'm agree. Give me instrutions.

**Comment by wjunkin** [comment] 2019-05-03 12:54
Hi, Dinis,
I am glad that you are testing out version 1.2.5 of Live Report.
I have created a quiz on a site where we hopefully can test things out and fix the problem.
Please go to 
https://www.lakeviewpresbyterianchurch.org/Moodle_34/
At this site I have installed Live Report version 1.2.5. The Moodle version is only 3.4 but I don't think that will make any difference.
You can log in as a teacher with username teacher1 and pwd of Teacher#1.
You can log in as a student with username student1 and pwd of Student#1.
I have already created a quiz with one essay question and you can use this to test things out to see if we can reproduce the problem. Of course, you are welcome to create other quizzes with other types of questions.
We will see if it is necessary to have the Portuguese language pack installed to reproduce the problem. Since I don't know Portuguese, I hope this will not be necessary.

**Comment by wjunkin** [comment] 2019-05-03 21:30
Hi, Dinis,
It looks like you have logged into the test course that I set up as a student, put some Portuguese text into the essay question, and then logged in as a teacher. The truncated text, the tootip, and the single question view (when you click on the question title) look fine to me. However, I don't know Portuguese.
1) If anything is displayed incorrectly, please let me know. Otherwise,
2) I encourage you to create a quiz with some question that will duplicate the error that you observed earlier. If you have a problem doing this and think that I should add the Protuguese language option to this Moodle site, please let me know and I will be happy to do this.
Thanks for your help in solving this problem.

**Comment by dinism** [comment] 2019-05-04 12:27
**NORMAL TABLE**
ALL is OK
![imagem](https://user-images.githubusercontent.com/14828021/57178752-38814f80-6e6d-11e9-9e15-624f24469a13.png)

**COMPACT TABLE**
TIP of responses and DESCRIPTION of columms OK .

![imagem](https://user-images.githubusercontent.com/14828021/57178838-995d5780-6e6e-11e9-8ed4-b6d59c50cc34.png)

I tried in different browsers, all with utf-8, and the problem is the same. 
I think the error is when the **4th letter of compacted word is a accented word** as you can see in image. 

![imagem](https://user-images.githubusercontent.com/14828021/57178950-2e148500-6e70-11e9-9941-3e509518b7c4.png)

**Comment by dinism** [comment] 2019-05-04 14:35
On your test site i replicated in the "3rd and 4th letter" test only the questions with problems and the results were:
**NORMAL table** all OK
![imagem](https://user-images.githubusercontent.com/14828021/57180314-5fe11800-6e7f-11e9-99f4-961b6c93df04.png)

**COMPACT Table** 
Here's the problem. My hypothesis is confirmed: when the 4th letter of the compacted word is accentuated, and it's in the last position, the error appears.
It happens in PT or EN language.
The description of the fields and the tooltip are not affected in any of the situations (compact and normal view).
The error is in the question name (column title) and in the table cells (responses).
Red arrows BAD. Green arrows OK

![imagem](https://user-images.githubusercontent.com/14828021/57180573-dc74f600-6e81-11e9-91c8-24a896799b29.png)

**I hope this can HELP you to SOLVE the problem!**

**Comment by wjunkin** [comment] 2019-05-04 18:16
Hi, Dinis,
I wrote the program to truncate the responses and the names of questions after a certain number of characters. For the regular view, the string is truncated after 40 characters while for the compact table view the string is runcated after 4 characters. (This choice of numbers is completely arbitrary but happens to be the one I selected.)
For letters with accents, tildas, etc., the html code for each of these symbols is a number of characters. For example, a with an accent is written &aacute; 
This means that if the string is truncated in the middle of these 8 characters, the html page won't know what to do with this partial string. I should be able to modify the program to take care of this problem. I'll let you know when I have done the modification. However, at this time I am leaving to visit family.

**Comment by wjunkin** [comment] 2019-05-30 10:05
Hi, Dinism,
I have now chaned the program so that when text is truncated, the truncation is not done in the middle of a word. I think this takes care of the problem that you noted so I am closing this issue. However, if you find that the new version has not taken care of this problem, please let me know and I will correct the problem. Thanks for bringing this to my attention.

**Closed as completed by wjunkin** 2019-05-30 10:05 UTC
